// AUTO-GENERATED by scaffold-workflow.cjs — do NOT hand-edit.
// Work-phase prompts come from --prompt/--prompts-file (data-in). To change a prompt OR the
// structure, re-run the generator with --force. A leftover \`TODO:\` means a prompt wasn't
// supplied — fill it by regenerating, not by editing this file.
//
// Conductor rules: pure JS only — no fs/git, no Date.now()/Math.random().
// All side-effects happen inside agent() subagents.
//
// Resume semantics: phases are AT-LEAST-ONCE on resume. We checkpoint AFTER the
// side-effect, so a crash between side-effect and checkpoint re-runs that phase.
// Every phase MUST therefore be idempotent. phasesDone is trusted only after the
// entry guard below validates it is a contiguous prefix of the phase order.

export const meta = {
  name: 'tiemquen-mvp',
  description: 'Build Tiệm Quen MVP per ARCH.md + docs/ENGINE-SPEC.md (self-built engine, mock-mode first)',
  phases: [
    { title: 'Setup' },
    { title: 'DoDBaseline' },
    { title: 'Foundation' },
    { title: 'Engine' },
    { title: 'ImportAgent' },
    { title: 'BuyerOrders' },
    { title: 'FlyerSeller' },
    { title: 'Verify' },
    { title: 'CodeGate' },
    { title: 'DoDGate' },
  ],
}

// Some Workflow harnesses deliver `args` as a JSON STRING rather than an object; normalize
// once here (BEFORE any args read) so every `(args && args.X)` guard below works either way.
// Uses only typeof + JSON.parse — both allowed at the restricted conductor layer.
if (typeof args === 'string') args = JSON.parse(args)

const NAME     = 'tiemquen-mvp'
const STATE    = `.workflows/state/${NAME}.json`
const BRANCH   = (args && args.branch) ? args.branch : `wf/${NAME}`
const BASE     = (args && args.base) ? args.base : 'main'
const WORKTREE = `.worktrees/${NAME}`
const TICKET   = (args && args.ticket) ? args.ticket : null
const DOD_CRITERIA = [{"id":"unit-tests","text":"Full unit test suite passes (pytest, all modules: a2ui validator/repair, compose, import, order state machine, notify fallback, vietqr CRC, qr batch).","tier":"checkable","check":"./.venv/bin/python -m pytest -q"},{"id":"e2e-mock","text":"End-to-end smoke runs WITHOUT any Gemini API key (mock mode): import fixture -> chuẩn menu -> compose valid A2UI -> cache -> place COD order -> state machine created->seller_seen->confirmed->done -> notify fallback fires -> group order split -> QR batch + VietQR payload + flyer PDF generated.","tier":"checkable","check":"env -u GEMINI_API_KEY ./.venv/bin/python scripts/e2e_smoke.py"},{"id":"artifacts-exist","text":"Core deliverable files exist: buyer renderer, seller PWA entry, menu schema, catalog.","tier":"checkable","check":"test -f buyer/renderer.js && test -f seller/index.html && test -f shared/menu_schema.json && test -f agents/tiemquen_agent/catalogs/tiemquen_emenu_v1.json"},{"id":"buyer-no-llm","text":"Golden rule (ARCH §5.1): no LLM call anywhere on the buyer path — buyer/ static assets and the order-serving endpoints (view menu, place order, order status) must not import or invoke google-genai or any LLM. LLM only in compose/import/flyer/order-parse (compose-time).","tier":"judged"},{"id":"readme-accurate","text":"README quickstart is accurate: a fresh dev can create venv, install, boot the server, open the demo shop buyer page and seller dashboard by following it verbatim.","tier":"judged"}]

const prior = (args && args.results) ? args.results : {}
const done  = new Set((args && args.phasesDone) ? args.phasesDone : [])
const results = { ...prior }

// --- Resume reachability guard: phasesDone MUST be a contiguous prefix ---
// Canonical order is baked in as a literal — the Workflow runtime consumes `meta` as
// metadata, so it is NOT a runtime binding in this body. A durable state that marks a
// phase done while an earlier phase is not is unreachable (corrupt/forged) — reject it
// loudly instead of silently skipping required setup work.
;(() => {
  const order = ["Setup","DoDBaseline","Foundation","Engine","ImportAgent","BuyerOrders","FlyerSeller","Verify","CodeGate","DoDGate"]
  for (const title of done) {
    if (!order.includes(title)) {
      throw new Error(`Unreachable resume: phasesDone has unknown phase '${title}' (not in order: ${order.join(' → ')})`)
    }
  }
  // Walk the order; once we hit the first NOT-done phase, no later phase may be done.
  let seenGap = false
  for (const title of order) {
    if (done.has(title)) {
      if (seenGap) {
        throw new Error(`Unreachable resume: phase '${title}' is done but an earlier required phase is not — phasesDone must be a contiguous prefix of [${order.join(' → ')}], got [${[...done].join(', ')}]`)
      }
    } else {
      seenGap = true
    }
  }
})()

// Per-worker instruction. `slot` makes the notes file UNIQUE so parallel / multiple agents
// never clobber each other. For a parallel fan-out, pass a slot unique per item (e.g. `phase-${i}`).
// Pass { notes: false } for mechanical steps (PR push, etc.) that make no design decisions —
// they should NOT create a notes file at all. Where notes ARE offered they are judgment-gated:
// write one ONLY if there is something a reviewer genuinely needs.
function inWorktree(slot, opts) {
  const base = `Work ONLY inside the git worktree at ${WORKTREE} (run \`cd ${WORKTREE}\` first; it is on ` +
    `branch ${BRANCH}). Do NOT edit any file outside ${WORKTREE}. Commit your changes there.`
  if (opts && opts.notes === false) return base
  return base + `\n\nIf — and ONLY if — this step involved a non-trivial design decision, an ` +
    `intentional deviation from the spec, a tradeoff between real alternatives, or an open question a ` +
    `reviewer must confirm, append it to a notes file UNIQUE to you at implementation-notes/${slot}.html ` +
    `in the worktree (mkdir -p the dir; create if missing; APPEND — never clobber). For mechanical or ` +
    `no-decision work, SKIP the file — do not create empty or boilerplate notes.`
}

// startedAt-preserving merge: cat clobbers the file, so read prev startedAt first.
async function checkpoint(phaseTitle) {
  const payload = JSON.stringify(
    { workflow: NAME, status: 'running', branch: BRANCH, worktree: WORKTREE, ticket: TICKET, dod: { criteria: DOD_CRITERIA }, phasesDone: [...done], results },
    null, 2,
  )
  await agent(
    `Persist durable workflow state to the MAIN repo (do NOT cd into the worktree). Run EXACTLY:

mkdir -p .workflows/state
cat > .workflows/state/.${NAME}.payload.json <<'DURABLE_JSON'
${payload}
DURABLE_JSON
node -e "const fs=require('fs');const f='${STATE}';const p='.workflows/state/.${NAME}.payload.json';let prev={};try{prev=JSON.parse(fs.readFileSync(f,'utf8'))}catch(e){};const s=JSON.parse(fs.readFileSync(p,'utf8'));const n=new Date().toISOString();s.startedAt=prev.startedAt||n;s.updatedAt=n;fs.writeFileSync(f,JSON.stringify(s,null,2));fs.unlinkSync(p)"
node -e "JSON.parse(require('fs').readFileSync('${STATE}','utf8'))" && echo OK

Return whether the file was written and parses.`,
    { label: `checkpoint:${phaseTitle}`, phase: phaseTitle,
      schema: { type: 'object', additionalProperties: false, required: ['written'], properties: { written: { type: 'boolean' }, path: { type: 'string' } } } },
  )
}

// --- Setup: create/reuse worktree + symlink node_modules (worktrees don't carry it) ---
phase('Setup')
if (done.has('Setup')) {
  log('Setup already complete (resumed)')
} else {
  results.setup = await agent(
    `Create an isolated git worktree. Run idempotently:

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "ERROR: not a git repo"; exit 1; }
ROOT="$(git rev-parse --show-toplevel)"
if git worktree list --porcelain | grep -q "/${WORKTREE}$"; then
  echo "worktree exists — reusing"
elif git show-ref --verify --quiet "refs/heads/${BRANCH}"; then
  git worktree add "${WORKTREE}" "${BRANCH}"
else
  # Branch from the FRESH remote tip, not a possibly-stale local ref.
  git fetch origin --quiet 2>/dev/null || echo "WARN: git fetch origin failed — using local refs (may be stale)"
  BASEREF="${BASE}"
  # Auto-detect the remote's default branch when no --base was given.
  [ -n "$BASEREF" ] || BASEREF="$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##')"
  if [ -n "$BASEREF" ] && git show-ref --verify --quiet "refs/remotes/origin/$BASEREF"; then
    START="origin/$BASEREF"
  elif [ -n "$BASEREF" ]; then
    echo "WARN: origin/$BASEREF not found — branching from local $BASEREF (may be stale)"; START="$BASEREF"
  else
    echo "WARN: could not detect remote default branch — branching from current HEAD (may be stale)"; START="HEAD"
  fi
  echo "Branching ${BRANCH} from $START"
  git worktree add "${WORKTREE}" -b "${BRANCH}" "$START"
fi
[ -e "${WORKTREE}/node_modules" ] || [ ! -d "$ROOT/node_modules" ] || ln -s "$ROOT/node_modules" "${WORKTREE}/node_modules"
test -d "${WORKTREE}" && echo OK`,
    { label: 'setup:worktree', phase: 'Setup',
      schema: { type: 'object', additionalProperties: false, required: ['ready'], properties: { ready: { type: 'boolean' }, worktree: { type: 'string' }, branch: { type: 'string' } } } },
  )
  done.add('Setup')
  await checkpoint('Setup')
}

phase('DoDBaseline')
if (done.has('DoDBaseline')) {
  log('DoDBaseline already complete (resumed)')
} else {
  results.dodBaseline = await agent(
    `${inWorktree('dod-baseline', { notes: false })}

DoD BASELINE (pre-work measurement): for EACH criterion below, run its "check" command inside ${WORKTREE} and record met (exit 0) / unmet (non-zero) / error (could not run). Do NOT fix anything — measure only.

CHECKABLE CRITERIA (JSON): ${JSON.stringify(DOD_CRITERIA.filter((c) => c.tier === 'checkable'))}`,
    { label: 'dod-baseline', phase: 'DoDBaseline', schema: { type: 'object', additionalProperties: false, required: ["baselines"], properties: {"baselines":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["id","status"],"properties":{"id":{"type":"string"},"status":{"type":"string","enum":["met","unmet","error"]}}}}} } },
  )
  done.add('DoDBaseline')
  await checkpoint('DoDBaseline')
}

phase('Foundation')
if (done.has('Foundation')) {
  log('Foundation already complete (resumed)')
} else {
  results.foundation = await agent(
    `${inWorktree('Foundation')}

FIRST read ARCH.md and docs/ENGINE-SPEC.md at the worktree root — they are the source of truth (repo layout: SPEC §3; menu schema: SPEC §4). Build the monorepo foundation:
1. Python env: \`python3 -m venv .venv\`, requirements.txt with fastapi, uvicorn[standard], pydantic>=2, pytest, httpx, jsonschema, qrcode[pil], pillow, reportlab, google-genai, beautifulsoup4, requests. \`./.venv/bin/pip install -r requirements.txt\` and verify imports.
2. shared/menu_schema.json — JSON Schema for the chuẩn menu format (SPEC §4, this is the core data model every later phase reads; be thorough: shop info incl payment cod/vietqr + direct_discount_pct + theme.seed_colors, menu.sections + menu.dishes with price/platform_price/direct_only/hidden/sold_out/almost_out, source block). Plus shared/order_states.py listing order states (SPEC §8).
3. data/fixtures/demo_shop.json — realistic Vietnamese cơm văn phòng shop (Cơm Tấm Cô Ba: ~3 sections, 10 dishes with VND prices, platform_price ~15% higher) validating against the schema.
4. infra/storage.py — storage adapter: interface get/put/list/delete per collection; LocalJSONStorage writing under data/ (dirs per collection); designed so a Firestore impl can swap in later.
5. infra/publish.py — per-shop slug registry (slugify VN names, uniqueness, reserved words).
6. agents/tiemquen_agent/server.py — FastAPI app factory with /health, minimal shops CRUD (create from fixture, get by slug), CORS, static mounts for buyer/ seller/ data/media/. Entry: \`./.venv/bin/uvicorn agents.tiemquen_agent.server:app\`. Add __init__.py files so packages import cleanly from repo root.
7. scripts/e2e_smoke.py — end-to-end smoke script that MUST run with no GEMINI_API_KEY (mock mode) and exit 0. In this phase it: validates fixture against schema, creates shop via storage, resolves slug, boots the app with httpx ASGI client and asserts /health + get-shop. LATER PHASES EXTEND THIS SCRIPT — structure it as numbered steps with clear section comments.
8. tests/ — pytest for schema validation (good + bad fixture), storage adapter, slug registry, health endpoint. All green via \`./.venv/bin/python -m pytest -q\`.
9. README.md — quickstart (venv, install, run server, run tests, run smoke).
Note .gitignore already excludes .venv and data/media. Commit everything (including data/fixtures) with a clear message.`,
    { label: 'foundation', phase: 'Foundation', schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
  )
  done.add('Foundation')
  await checkpoint('Foundation')
}

phase('Engine')
if (done.has('Engine')) {
  log('Engine already complete (resumed)')
} else {
  results.engine = await agent(
    `${inWorktree('Engine')}

FIRST read docs/ENGINE-SPEC.md §1 §2 §6-theme §7 and ARCH.md §5. Build the compose engine (LLM compose-time only):
1. agents/tiemquen_agent/a2ui.py — A2UI v0.9 protocol per SPEC §1: builders make_create_surface/make_update_components/make_update_data_model/make_delete_surface; parse + validate + REPAIR: inject missing version, infer missing action key from payload shape (components→updateComponents, catalogId→createSurface, path+value→updateDataModel), ensure_create_surface auto-prepend, flat-wire component checks (id/component present, root exists, childIds shapes: childId | childIds.explicitList | childIds.dataBinding, leaf values path|literalString|literalNumber|literalBoolean, event shape). Validator returns (clean_messages, warnings).
2. agents/tiemquen_agent/catalogs/tiemquen_emenu_v1.json — component catalog per SPEC §2: Page, MenuSection, HeroHeader, Badge, DishCard, ComboCard, ReorderCard, CartBar, GroupOrderButton, ReviewStrip, CheckoutForm, PaymentPicker, OrderStatus — each entry JSON-Schema (type/properties with descriptions/required). This doubles as composer prompt documentation.
3. compose/theme.py — derive full palette (bg, surface, text tiers, accent, success/warn) from 4 seed hex colors + WCAG contrast check ≥4.5 for text pairs; deterministic.
4. compose/composer.py — compose(menu_chuẩn, theme, variant) → validated A2UI message list. MOCK MODE (no GEMINI_API_KEY env): deterministic template composer building the full surface from the menu (HeroHeader, sections with DishCards bound to /prices and /soldout DataModel paths, CartBar, CheckoutForm COD, GroupOrderButton) — no network. REAL MODE: google-genai (model gemini-flash-latest) with catalog JSON in prompt, response wrapped in <a2ui-json> tags, parse → validate/repair → one retry with correction prompt on failure. Compose VARIANTS per ARCH §5.3: office vs table batch, lunch vs regular — cached separately.
5. compose/racing.py — race_compose(n): asyncio N identical compose calls, first valid wins, cancel losers; only used in real mode; RACE_ENABLED/RACE_COUNT env.
6. compose/cache.py — write composed variants to data/composed/<slug>/<variant>.json; sold-out/price changes are updateDataModel PATCHES appended (no structural recompose) — implement patch_data(slug, path, value).
7. Server endpoints: POST /shops/{slug}/compose (recompose all variants), POST /shops/{slug}/patch (soldout/price patch). 
8. Tests: validator repair cases (missing version, missing action key each shape, missing createSurface, bad component refs), theme contrast, mock compose produces valid messages + all catalog components used are in catalog, patch flow. Extend scripts/e2e_smoke.py: fixture menu → mock compose (all 4 variants) → validate → cache files exist → patch sold_out → cached JSON contains the patch. All pytest green. Commit.`,
    { label: 'engine', phase: 'Engine', schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
  )
  done.add('Engine')
  await checkpoint('Engine')
}

phase('ImportAgent')
if (done.has('ImportAgent')) {
  log('ImportAgent already complete (resumed)')
} else {
  results.importAgent = await agent(
    `${inWorktree('ImportAgent')}

FIRST read docs/ENGINE-SPEC.md §5 and ARCH.md §3.1. Build the import pipeline (OCR = đường chính):
1. agents/tiemquen_agent/toolable.py — function-calling harness: given typed Python tool functions (docstring = model-facing spec), run a google-genai tool-calling loop, harvest calls, return {"tool_calls": [...], "message": str}. Strip additionalProperties from generated schemas. MOCK MODE: accepts a pre-recorded tool-call list and replays it through the same assembly path (so mock and real share 100% of the assembly code).
2. agents/tiemquen_agent/tools/menu_tools.py — set_shop_info(name, phone?, address?, hours?), add_section(id, title), add_dish(section_id, name, price, desc?, image_ref?), finish(confidence, warnings) — assembling into the chuẩn menu format (shared/menu_schema.json), validating price sanity (VND, 5k–500k warn).
3. agents/tiemquen_agent/agents/import_agent.py — entry import_menu(source): source = screenshot path(s) | URL | raw text. Screenshot → REAL: google-genai multimodal (image parts + OCR prompt forcing menu_tools calls); MOCK (no GEMINI_API_KEY): load data/fixtures/grab_screenshot_toolcalls.json (create it: realistic simulated OCR tool-calls for the demo shop) and replay. URL → html_parse.py best-effort ShopeeFood parse (requests+bs4, graceful fail → raise ImportFallbackToOCR). Output envelope: {menu, warnings, confidence} per SPEC §5.
4. Image rehost stub: infra/media.py — copy/download dish images into data/media/<shop>/, rewrite image_url to /media/... paths.
5. Server endpoints: POST /import (json body: url or fixture ref; multipart screenshot), GET /shops/{slug}/menu, PATCH /shops/{slug}/menu (review edits: price change, hide dish, add direct_only dish, section retitle) — PATCH triggers recompose via compose pipeline.
6. Tests: toolable mock replay → valid chuẩn menu; price sanity warnings; html_parse graceful failure; PATCH → recompose called (monkeypatch). Extend scripts/e2e_smoke.py: mock import fixture → chuẩn menu validates → PATCH price -10% → recompose → composed cache updated. All pytest green. Commit.`,
    { label: 'importAgent', phase: 'ImportAgent', schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
  )
  done.add('ImportAgent')
  await checkpoint('ImportAgent')
}

phase('BuyerOrders')
if (done.has('BuyerOrders')) {
  log('BuyerOrders already complete (resumed)')
} else {
  results.buyerOrders = await agent(
    `${inWorktree('BuyerOrders')}

FIRST read docs/ENGINE-SPEC.md §1 §8 §9 and ARCH.md §3.2 §3.3 §5.3. Build buyer page + orders + notify (ZERO LLM on this path — golden rule):
1. buyer/index.html + buyer/renderer.js (~200-300 lines vanilla JS, no framework, no build step): fetch cached A2UI JSON for slug+variant, walk the flat component list (root id="root", childId/childIds.explicitList/childIds.dataBinding), resolve {path}/{literal*} values against the DataModel, render semantic HTML for every catalog component (DishCard with price VND format + soldOut hiding, CartBar sticky, CheckoutForm, etc.), dispatch component events (add_to_cart etc.) to order.js. Apply theme palette via CSS variables. Total buyer payload target <150KB.
2. buyer/context_rules.js — SPEC §9: read ?b= batch tag (office→promote GroupOrderButton + pick office variant), local hour 10–13 → lunch variant/section first, localStorage last_order → prepend ReorderCard, fetch soldout patch JSON and apply as DataModel patch. Pure rules, no LLM.
3. buyer/order.js — cart state, checkout COD (name, phone, address/toà nhà, note), POST /orders, then poll GET /orders/{id}/status showing 'quán đã thấy đơn' when seller_seen; re-order storage in localStorage.
4. infra/orders.py — state machine per SPEC §8: created→seller_seen→confirmed→delivering→done | cancelled | no_show_flagged; explicit allowed-transition table, invalid transition raises; persisted via storage adapter; every order stores batch_id for flyer analytics.
5. infra/notify.py — pipeline: on created → push via channel chain [FCMWebPushStub, ConsoleChannel]; ack timer (asyncio, ACK_TIMEOUT_SECONDS env default 120, tests use 0.1) → if not seller_seen fire SMSStubChannel (logs 'SMS to <phone>: <order summary>'). All adapters share one Channel interface so real FCM/SMS drop in later.
6. Group orders (ARCH §3.3): POST /group-orders (from shop+batch) → share URL /g/{gid}; buyer/group.html: members add name + items into one order; closer closes → single order created + per-member split amounts + per-member VietQR placeholder (interface only, vietqr real in next phase); GET /group-orders/{gid} state.
7. agents/tiemquen_agent/agents/order_parse_agent.py — parse pasted Zalo chat text → order draft: MOCK mode = deterministic heuristic parser (dish-name fuzzy match against menu + quantities + address line); REAL mode = toolable with add_item/set_customer tools. Endpoint POST /orders/parse-text.
8. Server: serve buyer at GET /t/{slug} (inject slug+variant list), mount /g/{gid}; seller ack endpoint POST /orders/{id}/ack + transitions endpoint.
9. Tests: state machine table (all legal + illegal transitions), notify fallback timing (fast timeout), group order split math (uneven totals), order-parse heuristic on 3 sample chat texts, buyer page endpoint returns HTML containing renderer.js. Extend scripts/e2e_smoke.py: place COD order → notify console fired → ack → seller_seen visible in status → confirm → done; group order 3 members → split correct. All pytest green. Commit.`,
    { label: 'buyerOrders', phase: 'BuyerOrders', schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
  )
  done.add('BuyerOrders')
  await checkpoint('BuyerOrders')
}

phase('FlyerSeller')
if (done.has('FlyerSeller')) {
  log('FlyerSeller already complete (resumed)')
} else {
  results.flyerSeller = await agent(
    `${inWorktree('FlyerSeller')}

FIRST read docs/ENGINE-SPEC.md §6 and ARCH.md §2 §3.1 §4.4. Build flyer generation + seller PWA:
1. agents/tiemquen_agent/imagen.py — gen hero/flyer background: REAL mode google-genai generate_content response_modalities=[TEXT,IMAGE], aspect ratio per format (A5/A4 portrait, sticker square), sanitize pre-pass via cheap model, hard constraints REPEATED at end of prompt, ask for palette JSON (4 seed hex) alongside image, one retry if text-only; MOCK mode: Pillow-generated placeholder (solid seed-color bg + shop name text) so the whole flyer path works offline. Cache PNGs to data/media/<shop>/ with TTL cleanup helper.
2. infra/qr_batch.py — batch registry: create_batch(shop, format, location_tag) → batch_id; QR URL = /t/{slug}?b={batch_id}; orders already store batch_id — add analytics query orders_per_batch(shop, since).
3. infra/vietqr.py — EMVCo TLV VietQR payload (NAPAS: bank BIN, account, amount, message) with correct CRC16-CCITT; unit-test against a known-good reference vector; render QR PNG via qrcode lib; helper deep_link + copy-text ('copy số TK + số tiền').
4. infra/pdf_export.py — flyer PDF per format: A5 (order-bag insert), A4 (pantry poster), sticker (square): hero image full-bleed, shop name + tagline, 3 best-seller dishes with prices, big CTA 'THÈM? QUÉT.', batch QR bottom-right in the safe zone, print-ready (reportlab, mm sizes, 300dpi images). export_flyers(shop, batch_ids) → data/media/<shop>/flyer_<format>.pdf.
5. seller/ web PWA (vanilla JS, no build): index.html + app.js with 3 tabs — (a) Onboard wizard: paste URL / pick fixture screenshot → review table (editable prices, hide toggles, add direct-only dish) → 3 interview questions (ship zone, payment, direct discount %) → publish (calls import + PATCH + compose); (b) Đơn: live order list (poll), ACK button ('Đã thấy đơn'), status advance buttons, đơn-theo-batch counts; (c) Tờ rơi: pick format → generate → download PDF links. manifest.json + minimal sw.js (cache shell) so it installs as PWA.
6. Server: endpoints for batches CRUD, flyer generate/download, batch analytics; mount seller/ at /seller.
7. Tests: vietqr CRC reference vector + payload field order, batch analytics counting, pdf files created with >10KB size, imagen mock produces PNG. Extend scripts/e2e_smoke.py: create A5+A4 batches → mock imagen → export flyers → PDFs exist → vietqr payload for group-split member validates CRC. All pytest green. Commit.`,
    { label: 'flyerSeller', phase: 'FlyerSeller', schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
  )
  done.add('FlyerSeller')
  await checkpoint('FlyerSeller')
}

phase('Verify')
if (done.has('Verify')) {
  log('Verify already complete (resumed)')
} else {
  results.verify = await agent(
    `${inWorktree('Verify')}

Full verification sweep of the Tiệm Quen MVP in this worktree. DO NOT assume — run everything:
1. Fresh-install check: delete and recreate .venv, \`./.venv/bin/pip install -r requirements.txt\`.
2. \`./.venv/bin/python -m pytest -q\` — fix any failure.
3. \`env -u GEMINI_API_KEY ./.venv/bin/python scripts/e2e_smoke.py\` — must exit 0 covering: fixture import → chuẩn menu → compose 4 variants → patch → COD order lifecycle → notify fallback → group order split → batches → flyers PDFs → vietqr CRC.
4. Boot the real server (\`./.venv/bin/uvicorn agents.tiemquen_agent.server:app --port 8787 &\`), then curl: /health, seed demo shop, /t/<slug> returns HTML referencing renderer.js, POST /orders round-trip, seller page /seller loads, flyer download works. Kill server after.
5. Golden-rule audit: grep the buyer/ dir and the order-serving endpoints for any google-genai/LLM usage — must be none; record findings.
6. Measure buyer payload (index.html + renderer.js + context_rules.js + order.js + composed JSON for demo shop) — record total KB vs <150KB target.
7. Update README.md so quickstart matches reality verbatim (venv, install, uvicorn command, demo shop seed, buyer URL, seller URL, smoke + tests commands).
8. Write VERIFY.md: what was run, results, payload size, known gaps / deferred items (real Gemini calls untested without key, FCM/SMS are stubs, etc.).
Fix everything broken; leave the tree green. Commit.`,
    { label: 'verify', phase: 'Verify', schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
  )
  done.add('Verify')
  await checkpoint('Verify')
}

phase('CodeGate')
if (done.has('CodeGate')) {
  log('CodeGate already complete (resumed)')
} else {
  let passed = false, last = null
  for (let round = 1; round <= 3 && !passed; round++) {
    const dod = results.brief ? `\n\nScope this gate to the task's actual goal — judge findings against what the task set out to achieve; do NOT drift into changes unrelated to it.\nGOAL: ${results.brief.goal || '(none)'}` + ((results.brief.acceptanceCriteria || []).length ? `\nACCEPTANCE CRITERIA:\n- ${results.brief.acceptanceCriteria.join('\n- ')}` : '') : ''
    const carry = round > 1 && last ? `\n\nROUND ${round} of up to 3 — a prior round already ran; BUILD ON what it already found/fixed, do NOT re-review from scratch. Prior round summary: ${last.summary || '(no summary)'}` : ''
    last = await agent(
      `${inWorktree('codegate')}

Review AND fix the changes on branch ${BRANCH} relative to ${BASE || 'the base branch'} (run git diff in ${WORKTREE}). Run the project build/lint — it MUST pass. Resolve EVERY Critical and High finding (bugs, security, rule violations, quality). Re-run the build after fixes and commit them.` + dod + carry,
      { label: `codegate:r${round}`, phase: 'CodeGate', agentType: 'lirbox:lirbox-code-reviewer',
        schema: { type: 'object', additionalProperties: false, required: ["gatePassed"], properties: {"gatePassed":{"type":"boolean"},"critical":{"type":"number"},"high":{"type":"number"},"summary":{"type":"string"}} } },
    )
    passed = last && last.gatePassed
  }
  if (!passed) throw new Error('CodeGate failed: unresolved Critical/High after 3 rounds — ' + (last && last.summary || ''))
  results.codeGate = last
  done.add('CodeGate')
  await checkpoint('CodeGate')
}

phase('DoDGate')
if (done.has('DoDGate')) {
  log('DoDGate already complete (resumed)')
} else {
  let dodPassed = false, dodLast = null
  for (let round = 1; round <= 3 && !dodPassed; round++) {
    dodLast = await agent(
      `${inWorktree('dodgate-verify', { notes: false })}

DoD VERIFY (round ${round}/3) — MEASURE ONLY, do NOT fix anything. Adjudicate EVERY criterion below against the work on ${BRANCH} vs ${BASE || 'the base branch'}:
- tier "checkable": run the "check" command inside ${WORKTREE}; exit 0 = MET, non-zero = UNMET; the command output is the evidence.
- tier "judged": verdict from real evidence you CITE (file:line, command output, test result). No evidence = not MET.
Verdicts: MET | UNMET | PARTIAL.

CRITERIA (JSON): ${JSON.stringify(DOD_CRITERIA)}`,
      { label: `dodgate:verify-r${round}`, phase: 'DoDGate',
        schema: { type: 'object', additionalProperties: false, required: ["criteria"], properties: {"criteria":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["id","verdict","evidence"],"properties":{"id":{"type":"string"},"verdict":{"type":"string","enum":["MET","UNMET","PARTIAL"]},"evidence":{"type":"string"}}}}} } },
    )
    const unmet = ((dodLast && dodLast.criteria) || []).filter((c) => c.verdict !== 'MET')
    dodPassed = !!(dodLast && (dodLast.criteria || []).length && unmet.length === 0)
    if (!dodPassed && round < 3) {
      await agent(
        `${inWorktree('dodgate-fix')}

DoD FIX (round ${round}/3): the definition-of-done criteria below are NOT met. Make them met — implement what is missing, run the relevant checks yourself, then re-run the project test suite (your fix must not regress it) and commit. Do NOT weaken, game, or delete a check; if a criterion is genuinely impossible, say so in the summary instead of faking it.

UNMET (JSON): ${JSON.stringify(unmet)}
FULL DoD (JSON): ${JSON.stringify(DOD_CRITERIA)}`,
        { label: `dodgate:fix-r${round}`, phase: 'DoDGate',
          schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"},"fixed":{"type":"array","items":{"type":"string"}}} } },
      )
    }
  }
  results.dodGate = dodLast
  if (!dodPassed) throw new Error('DoDGate failed: DoD not fully met after 3 rounds — unmet: ' + ((dodLast && dodLast.criteria) || []).filter((c) => c.verdict !== 'MET').map((c) => c.id).join(', '))
  done.add('DoDGate')
  await checkpoint('DoDGate')
}

return { workflow: NAME, status: 'complete', branch: BRANCH, worktree: WORKTREE, ticket: TICKET, phasesDone: [...done], results }
